// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PCTechChoice.Data;
using System;

namespace PCTechChoice.Migrations
{
    [DbContext(typeof(PCTechContext))]
    partial class PCTechContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCTechChoice.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("BrandID");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("PCTechChoice.Models.Component", b =>
                {
                    b.Property<int>("BrandID");

                    b.Property<int>("ItemTypeID");

                    b.HasKey("BrandID", "ItemTypeID");

                    b.HasIndex("ItemTypeID");

                    b.ToTable("Component");
                });

            modelBuilder.Entity("PCTechChoice.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrandID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("ItemTypeID");

                    b.HasKey("FavoriteID");

                    b.HasIndex("BrandID");

                    b.HasIndex("ItemTypeID");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("PCTechChoice.Models.ItemType", b =>
                {
                    b.Property<int>("ItemTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ItemTypeID");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("PCTechChoice.Models.Component", b =>
                {
                    b.HasOne("PCTechChoice.Models.Brand", "Brand")
                        .WithMany("Components")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PCTechChoice.Models.ItemType", "Type")
                        .WithMany("Components")
                        .HasForeignKey("ItemTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PCTechChoice.Models.Favorite", b =>
                {
                    b.HasOne("PCTechChoice.Models.Brand", "Brand")
                        .WithMany("Favorites")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PCTechChoice.Models.ItemType", "ItemType")
                        .WithMany("Favorites")
                        .HasForeignKey("ItemTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
